insert into public.missions (
  slug,
  title,
  brand,
  product,
  reward_coins,
  difficulty,
  eta,
  category,
  description,
  hook,
  requirements,
  deliverables,
  tags,
  display_order,
  is_active,
  status
)
values
  (
    'community-dance-trend-reels',
    'Dance Trend Reels 任務挑戰',
    'Mission One Community',
    'Dance Trend Challenge',
    900,
    'Easy',
    '1 day',
    'Dance',
    '跟拍熱門 dance trend，重點係節奏、表情同鏡頭切換。',
    '首 2 秒先落最有記憶點動作，增加停留率。',
    array['影片長度 15-45 秒', '內容需原創拍攝', '需公開發佈 Reels', 'Caption 加 #MissionOneDanceTrend'],
    array['IG Reels 連結', '使用的 trend 名稱'],
    array['Community', 'Dance', 'Easy'],
    25,
    true,
    'active'
  ),
  (
    'community-reaction-duet-reels',
    'Reaction Duet Reels 任務挑戰',
    'Mission One Community',
    'Reaction Duet Challenge',
    900,
    'Easy',
    '1 day',
    'Entertainment',
    '用 duet/reaction 形式回應熱門片段，加入你個人觀點同情緒反應。',
    '前 3 秒清楚講出你要反應嘅重點，拉高完播率。',
    array['影片長度 15-60 秒', '需標示反應來源', '內容不可含侵權片段', 'Caption 加 #MissionOneReactionDuet'],
    array['IG Reels 連結', '原片來源或主題說明'],
    array['Community', 'Reaction', 'Easy'],
    26,
    true,
    'active'
  ),
  (
    'community-daily-vlog-reels',
    'Daily Vlog Reels 任務挑戰',
    'Mission One Community',
    'Daily Vlog Challenge',
    900,
    'Easy',
    '1 day',
    'Lifestyle',
    '拍攝你一日其中一段生活流程，例如上班前、健身後或夜晚放鬆時段。',
    '用「一日中的一刻」做開場，令觀眾快速代入。',
    array['影片長度 20-60 秒', '內容需真實且原創', '畫面需穩定清晰', 'Caption 加 #MissionOneDailyVlog'],
    array['IG Reels 連結', '一句 vlog 主題'],
    array['Community', 'Vlog', 'Easy'],
    27,
    true,
    'active'
  )
on conflict (slug) do update
set
  title = excluded.title,
  brand = excluded.brand,
  product = excluded.product,
  reward_coins = excluded.reward_coins,
  difficulty = excluded.difficulty,
  eta = excluded.eta,
  category = excluded.category,
  description = excluded.description,
  hook = excluded.hook,
  requirements = excluded.requirements,
  deliverables = excluded.deliverables,
  tags = excluded.tags,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  status = excluded.status;
