insert into public.missions (
  slug,
  title,
  brand,
  product,
  reward_coins,
  difficulty,
  eta,
  category,
  description,
  hook,
  requirements,
  deliverables,
  tags,
  display_order,
  is_active,
  status
)
values
  (
    'community-funny-reels',
    '搞笑 Reels 任務挑戰',
    'Mission One Community',
    'Funny Reels Challenge',
    950,
    'Easy',
    '1 day',
    'Entertainment',
    '拍一條搞笑短片，可以係日常反差、朋友互動、或者生活尷尬瞬間。',
    '用前 3 秒先落笑點，提升停留率同互動率。',
    array['影片長度 15-45 秒', '內容需原創並公開發佈', '不可包含攻擊性或不當內容', 'Caption 加 #MissionOneFunnyReels'],
    array['IG Reels 連結', '一句內容說明'],
    array['Community', 'Funny', 'Easy'],
    23,
    true,
    'active'
  ),
  (
    'community-singing-cover-reels',
    '唱歌 Cover Reels 任務挑戰',
    'Mission One Community',
    'Singing Cover Reels Challenge',
    950,
    'Easy',
    '1 day',
    'Music',
    '上載你唱歌 cover 的 Reels，可以清唱、伴奏或 remix 形式。',
    '首 5 秒直接入副歌或最精彩段落，提高完成觀看率。',
    array['影片長度 20-60 秒', '聲音需清晰可辨識', '內容需符合版權與平台規範', 'Caption 加 #MissionOneSingCover'],
    array['IG Reels 連結', '歌曲名稱或主題'],
    array['Community', 'Singing', 'Easy'],
    24,
    true,
    'active'
  )
on conflict (slug) do update
set
  title = excluded.title,
  brand = excluded.brand,
  product = excluded.product,
  reward_coins = excluded.reward_coins,
  difficulty = excluded.difficulty,
  eta = excluded.eta,
  category = excluded.category,
  description = excluded.description,
  hook = excluded.hook,
  requirements = excluded.requirements,
  deliverables = excluded.deliverables,
  tags = excluded.tags,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  status = excluded.status;
